syntax = "proto3";
package axis.api;
option java_package = "io.disys.axis.consensus.proto";
option java_multiple_files = true;
option java_outer_classname = "CommandProto";

import "kv.proto";
import "lease.proto";

message Command {
    int64 command_id = 1;
    oneof type {
        PutRequest                  put                    = 2;
        PutAndGetRequest            put_and_get            = 3;
        PutWithLeaseRequest         put_with_lease         = 4;
        PutWithLeaseAndGetRequest   put_with_lease_and_get = 5;
        UpdateLeaseRequest          update_lease           = 6;
        UpdateValueRequest          update_value           = 7;
        RemoveLeaseRequest          remove_lease           = 8;
        DeleteRequest               delete                 = 9;
        DeleteAndGetRequest         delete_and_get         = 10;
        DeleteRangeRequest          delete_range           = 11;
        DeleteRangeAndGetRequest    delete_range_and_get   = 12;
        TxnRequest                  txn                    = 13;
        CompactRequest              compact                = 14;
        GrantRequest                lease_grant            = 15;
        RevokeRequest               lease_revoke           = 16;
        LeaseCheckpoint             lease_checkpoint       = 17;
    }
}

message LeaseCheckpoint {
    message Entry {
        int64 lease_id      = 1;
        int64 remaining_ttl = 2;
    }
    repeated Entry entries = 1;
}
