package consensus.algorithm;

public enum ProposalDropReason {
    NO_LEADER,
    NO_DATA,
    LEADER_TRANSFER_IN_PROGRESS,
    REMOVED_FROM_CLUSTER,
    EXCEEDS_UNCOMMITTED_SIZE,
    FORWARDING_DISABLED,
    MEMBERSHIP_CHANGE_PENDING,
    NOT_IN_JOINT_CONFIG,
    MUST_LEAVE_JOINT_FIRST
}
